/* CompiladorExemploIntermediarioTotal.java */
/* Generated By:JavaCC: Do not edit this line. CompiladorExemploIntermediarioTotal.java */
import java.io.*;
import java.util.LinkedList;

public class CompiladorExemploIntermediarioTotal implements CompiladorExemploIntermediarioTotalConstants {
   static Tabela tabela = new Tabela();
   static LinkedList <Comando>  listaComandos;
   public static int ifref = 1;
   public static int printref = 1;
   public static void main(String args[])  throws ParseException  {
       // CompiladorExemplo analisador = null;
        try
   {
    CompiladorExemploIntermediarioTotal analisador = new CompiladorExemploIntermediarioTotal (System.in);
    listaComandos = analisador.inicio();
    System.out.println(listaComandos);
    GeradorCodigoDestino.geraCodigoAssembler(listaComandos);

    System.out.println("Compilado....");
  }
  catch(TokenMgrError e) {
  System.err.println("Lexical Error:\u005cn" + e.getMessage());
 }
  catch(ParseException e) {
  System.err.println("Syntactic Error:\u005cn" + e.getMessage());
  }
  catch(Exception e) {
  System.err.println("Semantic error:\u005cn" + e.getMessage()  );
  e.printStackTrace();
  }
 }

  static final public LinkedList <Comando> inicio() throws ParseException {Comando com=null; LinkedList<Comando> listaComandos = new LinkedList();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case PRINT:
      case IF:
      case SWITCH:
      case FOR:
      case WHILE:
      case DO:
      case DIV:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case PRINT:
      case IF:
      case SWITCH:
      case FOR:
      case WHILE:
      case DO:
      case IDENTIFICADOR:{
        com = linhaComando();
listaComandos.add(com);
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
        jj_consume_token(MULT);
        jj_consume_token(STRING);
        jj_consume_token(MULT);
        jj_consume_token(DIV);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
{if ("" != null) return listaComandos;}
    throw new Error("Missing return statement in function");
  }

////////////////////////////////////////////////////////////////////////////////
  static final public Comando linhaComando() throws ParseException {Comando com=null;
    if (jj_2_1(5)) {
      com = printa();
      jj_consume_token(PONTOVIRGULA);
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case IDENTIFICADOR:{
        com = atribui();
        jj_consume_token(PONTOVIRGULA);
        break;
        }
      case IF:{
        com = condicional();
        break;
        }
      case SWITCH:{
        com = Switch();
        break;
        }
      case WHILE:{
        com = iterativoWhile();
        break;
        }
      case FOR:{
        com = iterativoFor();
        break;
        }
      case DO:{
        com = iterativoDoWhile();
        jj_consume_token(PONTOVIRGULA);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

////////////////////////////////////////////////////////////////////////////////////
  static final public Comando printa() throws ParseException {Simbolo simb; Comando com=null; LinkedList<Item> listaExp = new LinkedList<Item>();
    jj_consume_token(PRINT);
    Or(listaExp);
simb = new Simbolo("_print" + printref, "STRING");
      tabela.inclui(simb);
      com = new Comando ('E', "_print" + printref, listaExp);
      printref +=1;
      {if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

////////////////////////////////////////////////////////////////////////////////////
  static final public Comando atribui() throws ParseException {Simbolo simb, simb2; Token t = null, tipo = null; Comando com=null, verificar = null, comandostrue = null, comandosfalse = null; LinkedList<Item> listaExp = new LinkedList<Item>(), listaExp2 = new LinkedList<Item>(), listaExp3 = new LinkedList<Item>(), listaExp4 = new LinkedList<Item>() ; LinkedList<Comando> listaComandosTrue = new LinkedList(), listaComandosFalse = new LinkedList(), verificacaoComando = new LinkedList();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO:{
      tipo = jj_consume_token(TIPO);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    t = jj_consume_token(IDENTIFICADOR);
if(tipo == null){
                  if(tabela.isExiste(t.image) == false){
                        System.err.println("Syntactic Error: variable " + t.image + " might not have been initialized");
                        System.exit(1);
                  }
            }
            else{
                  if(tabela.isExiste(t.image)){
                        System.err.println("Warning: variable " + t.image + " already defined, then it will have its updated value");
                  }
                  else{
                        if(tipo.image.equals("STRING")) simb = new Simbolo(removerAspas(t.image), tipo.image);
                        else simb = new Simbolo(t.image, tipo.image);
                        tabela.inclui(simb);
                  }
            }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIB:{
      jj_consume_token(ATRIB);
      Or(listaExp);
com = new Comando ('A',t.image,listaExp);
       {if ("" != null) return com;}
      break;
      }
    case OPERADOR_TERNARIO:{
      jj_consume_token(OPERADOR_TERNARIO);
      jj_consume_token(ABREPA);
      Or(listaExp2);
      jj_consume_token(FECHPA);
      jj_consume_token(INTERROGACAO);
      Or(listaExp3);
      jj_consume_token(DOIS_PONTOS);
      Or(listaExp4);
simb2 = new Simbolo("_cond" + ifref, "BOOL");
            tabela.inclui(simb2);
            verificar = new Comando ('A',"_cond"+ifref,listaExp2);
            verificacaoComando.add(verificar);
            listaExp.add(new Item('l', verificacaoComando));


            simb2 = new Simbolo("_true" + ifref, tipo.image);
            tabela.inclui(simb2);
            comandostrue = new Comando ('A',"_true"+ifref,listaExp3);
            listaComandosTrue.add(comandostrue);
            listaExp.add(new Item('l', listaComandosTrue));


            simb2 = new Simbolo("_false" + ifref, tipo.image);
            tabela.inclui(simb2);
            comandosfalse = new Comando ('A',"_false"+ifref,listaExp4);
            listaComandosFalse.add(comandosfalse);
            listaExp.add(new Item('l', listaComandosFalse));

            com = new Comando ('T', t.image , listaExp);
            ifref += 1;
            {if ("" != null) return com;}
      break;
      }
    case ADICAO:{
      jj_consume_token(ADICAO);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:{
        jj_consume_token(ADICAO);
listaExp.add(new Item('v', t.image));
            listaExp.add(new Item('i', "1"));
            listaExp.add(new Item('o', "+"));
            com = new Comando ('A',t.image,listaExp);
            {if ("" != null) return com;}
        break;
        }
      case ATRIB:{
        jj_consume_token(ATRIB);
listaExp.add(new Item('v', t.image));
        Or(listaExp);
listaExp.add(new Item('o', "+"));
            com = new Comando ('A',t.image,listaExp);
            {if ("" != null) return com;}
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    case SUB:{
      jj_consume_token(SUB);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUB:{
        jj_consume_token(SUB);
listaExp.add(new Item('v', t.image));
            listaExp.add(new Item('i', "1"));
            listaExp.add(new Item('o', "-"));
            com = new Comando ('A',t.image,listaExp);
            {if ("" != null) return com;}
        break;
        }
      case ATRIB:{
        jj_consume_token(ATRIB);
listaExp.add(new Item('v', t.image));
        Or(listaExp);
listaExp.add(new Item('o', "-"));
            com = new Comando ('A',t.image,listaExp);
            {if ("" != null) return com;}
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Comando condicional() throws ParseException {Simbolo simb; Comando com=null, verificar = null, comandostrue = null, comandosfalse = null; LinkedList<Item> listaExp = new LinkedList<Item>(), listaExp2 = new LinkedList<Item>() ; LinkedList<Comando> listaComandosTrue = new LinkedList(), listaComandosFalse = new LinkedList(), verificacaoComando = new LinkedList();
    jj_consume_token(IF);
    jj_consume_token(ABREPA);
    Or(listaExp2);
    jj_consume_token(FECHPA);
    jj_consume_token(THEN);
    jj_consume_token(ABRECH);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case PRINT:
      case IF:
      case SWITCH:
      case FOR:
      case WHILE:
      case DO:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      comandostrue = linhaComando();
listaComandosTrue.add(comandostrue);
    }
    jj_consume_token(FECHACH);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
      jj_consume_token(ABRECH);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPO:
        case PRINT:
        case IF:
        case SWITCH:
        case FOR:
        case WHILE:
        case DO:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        comandosfalse = linhaComando();
listaComandosFalse.add(comandosfalse);
      }
      jj_consume_token(FECHACH);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      ;
    }
simb = new Simbolo("_cond" + ifref, "BOOL");
            tabela.inclui(simb);
            verificar = new Comando ('A',"_cond"+ifref,listaExp2);
            verificacaoComando.add(verificar);
            listaExp.add(new Item('l', verificacaoComando));
            listaExp.add(new Item('l', listaComandosTrue));
            listaExp.add(new Item('l', listaComandosFalse));
            com = new Comando ('I', "_cond"+ifref , listaExp);
            ifref += 1;
            {if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

  static final public Comando Switch() throws ParseException {Item caso = null; Simbolo simb = null; Comando com=null, verificar = null, comandoscase = null, comandosdefault = null; LinkedList<Item> listaExp = new LinkedList<Item>(), listaExp2 = new LinkedList<Item>() ; LinkedList<Comando> listaComandosCase = new LinkedList(), listaComandosDefault = new LinkedList(), verificacaoComando = new LinkedList();
    jj_consume_token(SWITCH);
    jj_consume_token(ABREPA);
    expressao1(listaExp2);
simb = new Simbolo("_cond" + ifref, null);
            tabela.inclui(simb);
            verificar = new Comando ('A',"_cond"+ifref,listaExp2);
            verificacaoComando.add(verificar);
            listaExp.add(new Item('l', verificacaoComando));
    jj_consume_token(FECHPA);
    jj_consume_token(ABRECH);
    label_4:
    while (true) {
      jj_consume_token(CASE);
      caso = fator();
      jj_consume_token(DOIS_PONTOS);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPO:
        case PRINT:
        case IF:
        case SWITCH:
        case FOR:
        case WHILE:
        case DO:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_5;
        }
        comandoscase = linhaComando();
listaComandosCase.add(comandoscase);
      }
listaExp.add(caso);
            listaExp.add(new Item('l', listaComandosCase));
            listaComandosCase = new LinkedList();
      jj_consume_token(BREAK);
      jj_consume_token(PONTOVIRGULA);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_4;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULT_SW:{
      jj_consume_token(DEFAULT_SW);
      jj_consume_token(DOIS_PONTOS);
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TIPO:
        case PRINT:
        case IF:
        case SWITCH:
        case FOR:
        case WHILE:
        case DO:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_6;
        }
        comandosdefault = linhaComando();
listaComandosDefault.add(comandosdefault);
      }
listaExp.add(new Item('o', "Default"));
            listaExp.add(new Item('l', listaComandosDefault));
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(FECHACH);
com = new Comando ('S', "_cond"+ifref , listaExp);
            ifref += 1;
            {if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

  static final public Comando iterativoWhile() throws ParseException {Simbolo simb; Comando com=null, verificar = null, comandostrue = null; LinkedList<Item> listaExp = new LinkedList<Item>(), listaExp2 = new LinkedList<Item>() ; LinkedList<Comando> listaComandosTrue = new LinkedList(), verificacaoComando = new LinkedList();
    jj_consume_token(WHILE);
    jj_consume_token(ABREPA);
    Or(listaExp2);
    jj_consume_token(FECHPA);
    jj_consume_token(ABRECH);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case PRINT:
      case IF:
      case SWITCH:
      case FOR:
      case WHILE:
      case DO:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_7;
      }
      comandostrue = linhaComando();
listaComandosTrue.add(comandostrue);
    }
    jj_consume_token(FECHACH);
simb = new Simbolo("_cond" + ifref, "BOOL");
            tabela.inclui(simb);
            verificar = new Comando ('A',"_cond"+ifref,listaExp2);
            verificacaoComando.add(verificar);
            listaExp.add(new Item('l', verificacaoComando));
            listaExp.add(new Item('l', listaComandosTrue));
            com = new Comando ('W', "_cond"+ifref , listaExp);
            ifref += 1;
            {if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

  static final public Comando iterativoFor() throws ParseException {Simbolo simb; Comando com=null, verificar = null, comandos1 = null, comandos2 = null, comandostrue; LinkedList<Item> listaExp = new LinkedList<Item>(), listaExp2 = new LinkedList<Item>() ; LinkedList<Comando> listaComandosTrue = new LinkedList(), verificacaoComando = new LinkedList(), comandoAtrib = new LinkedList(), comandoItera = new LinkedList();
    jj_consume_token(FOR);
    jj_consume_token(ABREPA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO:
    case IDENTIFICADOR:{
      comandos1 = atribui();
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(PONTOVIRGULA);
    Or(listaExp2);
    jj_consume_token(PONTOVIRGULA);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case TIPO:
    case IDENTIFICADOR:{
      comandos2 = atribui();
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    jj_consume_token(FECHPA);
    jj_consume_token(ABRECH);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case PRINT:
      case IF:
      case SWITCH:
      case FOR:
      case WHILE:
      case DO:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_8;
      }
      comandostrue = linhaComando();
listaComandosTrue.add(comandostrue);
    }
    jj_consume_token(FECHACH);
comandoAtrib.add(comandos1);
            listaExp.add(new Item('l', comandoAtrib));

            simb = new Simbolo("_cond" + ifref, "BOOL");
            tabela.inclui(simb);
            verificar = new Comando ('A',"_cond"+ifref,listaExp2);
            verificacaoComando.add(verificar);
            listaExp.add(new Item('l', verificacaoComando));

            listaExp.add(new Item('l', listaComandosTrue));

            comandoItera.add(comandos2);
            listaExp.add(new Item('l', comandoItera));

            com = new Comando ('F', "_cond"+ifref , listaExp);
            ifref += 1;
            {if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

  static final public Comando iterativoDoWhile() throws ParseException {Simbolo simb; Comando com=null, verificar = null, comandostrue = null; LinkedList<Item> listaExp = new LinkedList<Item>(), listaExp2 = new LinkedList<Item>() ; LinkedList<Comando> listaComandosTrue = new LinkedList(), verificacaoComando = new LinkedList();
    jj_consume_token(DO);
    jj_consume_token(ABRECH);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TIPO:
      case PRINT:
      case IF:
      case SWITCH:
      case FOR:
      case WHILE:
      case DO:
      case IDENTIFICADOR:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_9;
      }
      comandostrue = linhaComando();
listaComandosTrue.add(comandostrue);
    }
    jj_consume_token(FECHACH);
    jj_consume_token(WHILE);
    jj_consume_token(ABREPA);
    Or(listaExp2);
    jj_consume_token(FECHPA);
simb = new Simbolo("_cond" + ifref, "BOOL");
            tabela.inclui(simb);
            verificar = new Comando ('A',"_cond"+ifref,listaExp2);
            verificacaoComando.add(verificar);
            listaExp.add(new Item('l', verificacaoComando));
            listaExp.add(new Item('l', listaComandosTrue));
            com = new Comando ('D', "_cond"+ifref , listaExp);
            ifref += 1;
            {if ("" != null) return com;}
    throw new Error("Missing return statement in function");
  }

//////////////////////////////////////////////////////////////////////////////////////
  static final public void Expressao(LinkedList <Item> listaExp) throws ParseException {Token op = null; Item item = null, item2 = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:
    case STRING:
    case CHAR:
    case NUM:
    case DIGITO:
    case ABREPA:{
      expressao1(listaExp);
      break;
      }
    case SUB:
    case NEGACAO:
    case SENTENCA_BOOLEANA:{
      item = fatorbooleano();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
if(item != null) listaExp.add(item);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OPERADOR:{
        ;
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        break label_10;
      }
      op = jj_consume_token(OPERADOR);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFICADOR:
      case STRING:
      case CHAR:
      case NUM:
      case DIGITO:
      case ABREPA:{
        expressao1(listaExp);
        break;
        }
      case SUB:
      case NEGACAO:
      case SENTENCA_BOOLEANA:{
        item2 = fatorbooleano();
        break;
        }
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
if(item2 != null) listaExp.add(item2);
            if(op != null) listaExp.add(new Item ('o', op.image));
    }
  }

  static final public void Or(LinkedList <Item> listaExp) throws ParseException {Token n = null;
    And(listaExp);
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        break label_11;
      }
      n = jj_consume_token(OR);
      And(listaExp);
if (n != null){
      listaExp.add(new Item ('o',"or")); // a b or
    }
    }
  }

  static final public void And(LinkedList <Item> listaExp) throws ParseException {Token m=null;
    OrBitwise(listaExp);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_12;
      }
      m = jj_consume_token(AND);
      OrBitwise(listaExp);
if (m!=null)
            listaExp.add(new Item ('o',"and")); // a b and

    }
  }

  static final public void OrBitwise(LinkedList <Item> listaExp) throws ParseException {Token m=null;
    xOrBitwise(listaExp);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ORB:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_13;
      }
      m = jj_consume_token(ORB);
      xOrBitwise(listaExp);
if (m!=null)
                  listaExp.add(new Item ('o',"orb")); // a b orb

    }
  }

  static final public void xOrBitwise(LinkedList <Item> listaExp) throws ParseException {Token m=null;
    AndBitwise(listaExp);
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case XOR:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_14;
      }
      m = jj_consume_token(XOR);
      AndBitwise(listaExp);
if (m!=null)
            listaExp.add(new Item ('o',"xorb")); // a b xorb

    }
  }

  static final public void AndBitwise(LinkedList <Item> listaExp) throws ParseException {Token m=null;
    Expressao(listaExp);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ANDB:{
        ;
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        break label_15;
      }
      m = jj_consume_token(ANDB);
      Expressao(listaExp);
if (m!=null)
            listaExp.add(new Item ('o',"andb")); // a b andb

    }
  }

  static final public void expressao1(LinkedList <Item> listaExp) throws ParseException {Token op=null;
    expressao2(listaExp);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:
      case SUB:{
        ;
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADICAO:{
        op = jj_consume_token(ADICAO);
        break;
        }
      case SUB:{
        op = jj_consume_token(SUB);
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expressao2(listaExp);
if(op.image.equals("+")){
                  listaExp.add(new Item ('o',"+")); // a b +
            }
            else if (op.image.equals("-")){
                  listaExp.add(new Item ('o',"-")); // a b -
            }
    }
  }

  static final public void expressao2(LinkedList <Item> listaExp) throws ParseException {Token op = null;
    expressao3(listaExp);
    label_17:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:{
        ;
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        break label_17;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        op = jj_consume_token(MULT);
        break;
        }
      case DIV:{
        op = jj_consume_token(DIV);
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expressao3(listaExp);
if( op.image.equals("*")){
                  listaExp.add(new Item ('o',"*")); // a b * 
            }
            else if(op.image.equals("/")){
                  listaExp.add(new Item ('o',"/")); // a b / 
            }
    }
  }

  static final public void expressao3(LinkedList <Item> listaExp) throws ParseException {Token op = null;
    expressao4(listaExp);
    label_18:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POTENCIACAO:
      case RADICIACAO:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_18;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case POTENCIACAO:{
        op = jj_consume_token(POTENCIACAO);
        break;
        }
      case RADICIACAO:{
        op = jj_consume_token(RADICIACAO);
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expressao4(listaExp);
if( op.image.equals("^")){
                  listaExp.add(new Item ('o',"^")); // a b ^    
            }
            else if(op.image.equals("~")){
                  listaExp.add(new Item ('o',"~")); // a b ~  
            }
    }
  }

  static final public void expressao4(LinkedList <Item> listaExp) throws ParseException {Item item=null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:
    case STRING:
    case CHAR:
    case NUM:
    case DIGITO:{
      item = fator();
listaExp.add(item);
      break;
      }
    case ABREPA:{
      jj_consume_token(ABREPA);
      Or(listaExp);
      jj_consume_token(FECHPA);
      break;
      }
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

////////////////////////////////////////////////////////////////////////////////////////
  static final public Item fatorbooleano() throws ParseException {Token t, negado = null, sinal = null; Item item=null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NEGACAO:{
      negado = jj_consume_token(NEGACAO);
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SUB:{
      sinal = jj_consume_token(SUB);
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SENTENCA_BOOLEANA:{
      t = jj_consume_token(SENTENCA_BOOLEANA);
if(negado != null){
                  if(t.image == "true")
                        item= new Item ('b', "false");
                  else
                        item= new Item ('b', "true");
            }
            else item= new Item ('b', t.image);
            {if ("" != null) return item;}
      break;
      }
    case IDENTIFICADOR:{
      t = jj_consume_token(IDENTIFICADOR);
if(!tabela.isExiste(t.image))
                  System.out.println("Erro sem\u00e2ntico \u005cn A vari\u00e1vel "+t.image+"n\u00e3o foi inicializada");
            if(sinal == null)
                  if(negado != null && tabela.getTipo(t.image).equals("BOOL")){
                        item= new Item ('v',"!" + t.image);
                  }
                  else if(negado != null){
                        System.err.println("Syntactic error: incompatible types: "+ tabela.getTipo(t.image) +" cannot be converted to BOOLEAN");
                        System.exit(1);
                  }
                  else  item= new Item ('v',t.image);
            else{
                  if(negado != null){
                        System.err.println("Syntactic error: incompatible types: "+ tabela.getTipo(t.image) +" cannot be converted to BOOLEAN");
                        System.exit(1);
                  }
                  item= new Item ('v',"-" + t.image);
            }
            {if ("" != null) return item;}
      break;
      }
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public Item fator() throws ParseException {Token t, sinal = null; Item item=null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      t = jj_consume_token(IDENTIFICADOR);
if(!tabela.isExiste(t.image))
                  System.out.println("Erro sem\u00e2ntico \u005cn A vari\u00e1vel "+t.image+"n\u00e3o foi inicializada");
            if(sinal == null)
                  item= new Item ('v',t.image);
            else
                  item= new Item ('v',"-" + t.image);
            {if ("" != null) return item;}
      break;
      }
    case DIGITO:{
      t = jj_consume_token(DIGITO);
if(sinal == null)
                  item= new Item ('i',t.image);
            else
                  item= new Item ('i',"-" + t.image);
            {if ("" != null) return item;}
      break;
      }
    case NUM:{
      t = jj_consume_token(NUM);
if(sinal == null)
                  item= new Item ('d',t.image);
            else
                  item= new Item ('d',"-" + t.image);
            {if ("" != null) return item;}
      break;
      }
    case CHAR:{
      t = jj_consume_token(CHAR);
item= new Item ('c',t.image);
            {if ("" != null) return item;}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
item= new Item ('s', removerAspas(t.image));
            {if ("" != null) return item;}
      break;
      }
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

//////////////////////////////////////////////////////////////////////////////////////
  static final public 
String removerAspas(String input) throws ParseException {
if (input.startsWith("'") && input.endsWith("'")) {
            {if ("" != null) return input.substring(1, input.length() - 1);}
        }
        {if ("" != null) return input;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_3R_51()
 {
    if (jj_scan_token(NUM)) return true;
    return false;
  }

  static private boolean jj_3R_43()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_scan_token(20)) return true;
    }
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_38()
 {
    if (jj_3R_42()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_43()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_30()
 {
    if (jj_scan_token(ANDB)) return true;
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_50()
 {
    if (jj_scan_token(DIGITO)) return true;
    return false;
  }

  static private boolean jj_3R_28()
 {
    if (jj_scan_token(XOR)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3R_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) return true;
    }
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_26()
 {
    if (jj_scan_token(ORB)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_19()
 {
    if (jj_scan_token(PRINT)) return true;
    if (jj_3R_20()) return true;
    return false;
  }

  static private boolean jj_3R_48()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_49()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_34()
 {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_19()) return true;
    if (jj_scan_token(PONTOVIRGULA)) return true;
    return false;
  }

  static private boolean jj_3R_37()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_24()
 {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  static private boolean jj_3R_27()
 {
    if (jj_3R_29()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_25()
 {
    if (jj_3R_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_23()
 {
    if (jj_3R_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_26()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_22()
 {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_21()) return true;
    return false;
  }

  static private boolean jj_3R_41()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_32()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_36()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_21()
 {
    if (jj_3R_23()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_24()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_40()
 {
    if (jj_scan_token(SENTENCA_BOOLEANA)) return true;
    return false;
  }

  static private boolean jj_3R_35()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(18)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    return false;
  }

  static private boolean jj_3R_20()
 {
    if (jj_3R_21()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_22()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_33()
 {
    if (jj_scan_token(OPERADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) {
    jj_scanpos = xsp;
    if (jj_3R_37()) return true;
    }
    return false;
  }

  static private boolean jj_3R_47()
 {
    if (jj_scan_token(ABREPA)) return true;
    if (jj_3R_20()) return true;
    if (jj_scan_token(FECHPA)) return true;
    return false;
  }

  static private boolean jj_3R_31()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_29()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_46()
 {
    if (jj_3R_48()) return true;
    return false;
  }

  static private boolean jj_3R_44()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) return true;
    }
    return false;
  }

  static private boolean jj_3R_53()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3R_45()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(21)) {
    jj_scanpos = xsp;
    if (jj_scan_token(22)) return true;
    }
    if (jj_3R_44()) return true;
    return false;
  }

  static private boolean jj_3R_42()
 {
    if (jj_3R_44()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_45()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_52()
 {
    if (jj_scan_token(CHAR)) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiladorExemploIntermediarioTotalTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[38];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x11c740,0x11c740,0x1c640,0x40,0x20000,0x40000,0x60000,0x1c740,0x1c740,0x80,0x1c740,0x800,0x1c740,0x1000,0x1c740,0x40,0x40,0x1c740,0x1c740,0x50040000,0x0,0x50040000,0x800000,0x2000000,0x1000000,0x8000000,0x4000000,0x60000,0x60000,0x180000,0x180000,0x600000,0x600000,0x0,0x10000000,0x40000,0x40000000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x1,0x1,0x1,0x0,0x800,0x800,0x880,0x1,0x1,0x0,0x1,0x0,0x1,0x0,0x1,0x1,0x1,0x1,0x1,0x406d,0x2,0x406d,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x406d,0x0,0x0,0x1,0x6d,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[1];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public CompiladorExemploIntermediarioTotal(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CompiladorExemploIntermediarioTotal(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorExemploIntermediarioTotalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public CompiladorExemploIntermediarioTotal(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorExemploIntermediarioTotalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public CompiladorExemploIntermediarioTotal(CompiladorExemploIntermediarioTotalTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(CompiladorExemploIntermediarioTotalTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 38; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[50];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 38; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 50; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
