/* Generated By:JavaCC: Do not edit this line. CompiladorExemploIntermediarioTotalConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorExemploIntermediarioTotalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXIBE = 5;
  /** RegularExpression Id. */
  int TIPO = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int PRINT = 8;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int SWITCH = 10;
  /** RegularExpression Id. */
  int CASE = 11;
  /** RegularExpression Id. */
  int DEFAULT_SW = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int FOR = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int DO = 16;
  /** RegularExpression Id. */
  int ADICAO = 17;
  /** RegularExpression Id. */
  int SUB = 18;
  /** RegularExpression Id. */
  int MULT = 19;
  /** RegularExpression Id. */
  int DIV = 20;
  /** RegularExpression Id. */
  int POTENCIACAO = 21;
  /** RegularExpression Id. */
  int RADICIACAO = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int ORB = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int ANDB = 26;
  /** RegularExpression Id. */
  int XOR = 27;
  /** RegularExpression Id. */
  int NEGACAO = 28;
  /** RegularExpression Id. */
  int THEN = 29;
  /** RegularExpression Id. */
  int SENTENCA_BOOLEANA = 30;
  /** RegularExpression Id. */
  int FUNC = 31;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 32;
  /** RegularExpression Id. */
  int OPERADOR = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int CHAR = 35;
  /** RegularExpression Id. */
  int LETRA = 36;
  /** RegularExpression Id. */
  int NUM = 37;
  /** RegularExpression Id. */
  int DIGITO = 38;
  /** RegularExpression Id. */
  int OPERADOR_TERNARIO = 39;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 40;
  /** RegularExpression Id. */
  int INTERROGACAO = 41;
  /** RegularExpression Id. */
  int PONTO = 42;
  /** RegularExpression Id. */
  int ATRIB = 43;
  /** RegularExpression Id. */
  int ABRECH = 44;
  /** RegularExpression Id. */
  int FECHACH = 45;
  /** RegularExpression Id. */
  int ABREPA = 46;
  /** RegularExpression Id. */
  int FECHPA = 47;
  /** RegularExpression Id. */
  int ASPAS = 48;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 49;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"exibe\"",
    "<TIPO>",
    "\"else\"",
    "\"print\"",
    "\"if\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"~\"",
    "\"||\"",
    "\"|\"",
    "\"&&\"",
    "\"&\"",
    "\"#\"",
    "\"!\"",
    "\"then\"",
    "<SENTENCA_BOOLEANA>",
    "<FUNC>",
    "<IDENTIFICADOR>",
    "<OPERADOR>",
    "<STRING>",
    "<CHAR>",
    "<LETRA>",
    "<NUM>",
    "<DIGITO>",
    "\":=\"",
    "\":\"",
    "\"?\"",
    "\".\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"\\\'\"",
    "\";\"",
  };

}
